export const POST_ADMIN_CREATE_USER = 'POST_ADMIN_CREATE_USER';
export const GET_ADMIN_USERS_LIST = 'GET_ADMIN_USERS_LIST';
export const GET_ADMIN_USERS_EXPORT_CSV = 'GET_ADMIN_USERS_EXPORT_CSV';
export const GET_ADMIN_USERS_IMPORT_CSV = 'GET_ADMIN_USERS_IMPORT_CSV';
export const GET_USERS_BY_KEYS = 'GET_USERS_BY_KEYS';

export const LEAVE_ADMIN_CREATE_USER = 'LEAVE_ADMIN_CREATE_USER';
export const LEAVE_GET_ADMIN_USERS_LIST = 'LEAVE_GET_ADMIN_USERS_LIST';
export const LEAVE_GET_ADMIN_USERS_EXPORT_CSV = 'LEAVE_GET_ADMIN_USERS_EXPORT_CSV';
export const LEAVE_GET_ADMIN_USERS_IMPORT_CSV = 'LEAVE_GET_ADMIN_USERS_IMPORT_CSV';
export const LEAVE_GET_USERS_BY_KEYS = 'LEAVE_GET_USERS_BY_KEYS';
