export const GET_MARKETPLACE_ACCESS_LIST = 'GET_MARKETPLACE_ACCESS_LIST';
export const POST_REQUEST_ACCESS = 'POST_REQUEST_ACCESS';
export const GET_LIST_OPTIONS_BY_USER = 'GET_LIST_OPTIONS_BY_USER';
export const PUT_REJECT_REQUEST = 'PUT_REJECT_REQUEST';
export const PUT_APPROVE_REQUEST = 'PUT_APPROVE_REQUEST';
export const GET_LIST_MARKETPLACE_APPROVE = 'GET_LIST_MARKETPLACE_APPROVE';

export const LEAVE_GET_MARKETPLACE_ACCESS_LIST = 'LEAVE_GET_MARKETPLACE_ACCESS_LIST';
export const LEAVE_POST_REQUEST_ACCESS = 'LEAVE_POST_REQUEST_ACCESS';
export const LEAVE_GET_LIST_OPTIONS_BY_USER = 'LEAVE_GET_LIST_OPTIONS_BY_USER';
export const LEAVE_PUT_REJECT_REQUEST = 'LEAVE_PUT_REJECT_REQUEST';
export const LEAVE_PUT_APPROVE_REQUEST = 'LEAVE_PUT_APPROVE_REQUEST';
export const LEAVE_GET_LIST_MARKETPLACE_APPROVE = 'LEAVE_GET_LIST_MARKETPLACE_APPROVE';
